version: '3.8'

services:
  sentiment:
    build: ./SentimentClassificationAPI
    restart: always
    ports:
      - 80:80
    # volumes:
    #   - ./volume/ai:/app/data

    # topic:
    #   build: ./TopicClassificationAPI
    #   restart: always
    #   ports:
    #     - 81:81

  management:
    build: ./DBManagementRestAPI
    command: ./entrypoint.sh
    depends_on:
      - db
    ports:
      - 8080:8080
    # volumes:
    #   - ./volume/app:/app/

    env_file:
      - ./.env.dev

  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./volume/db:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root

  mongo_bi:
    image: mongo-bi
    #container_name: mongo_bi
    build:
      context: ./MongoBIConnector
    #entrypoint: ['/bin/sh', '-c', 'sleep 100000']
    restart: always
    ports:
      - 3307:3307
    environment:
      # CONFIG_MONGO_BI_MONGO_USERNAME: root
      # CONFIG_MONGO_BI_MONGO_PASSWORD: root
      # CONFIG_MONGO_BI_AUTH: 1
      CONFIG_MONGO_BI_MONGO_URI: mongodb://db:27017
      CONFIG_MONGO_BI_VERY_VERBOSE: 1
      CONFIG_MONGO_BI_SCHEMA_REFRESH_INTERVAL_SECS: 60
      CONFIG_MONGO_BI_SSL_MODE: allowSSL
      CONFIG_MONGO_BI_SSL_PEM_KEY_FILE: /ssl/mongobi.pem
    volumes:
      - ./volume/mongo-bi/ssl:/ssl
    depends_on:
      - db

  superset:
    image: burnout-superset
    #container_name: burnout-superset
    build:
      context: ./Superset
    restart: always
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.9.45
    environment:
      ENABLE_DEV_MODE: 1
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@dev.local
      ADMIN_PASSWORD: admin
    ports:
      - 8088:8088
    depends_on:
      - db
    # volumes:
    #   - ./volume/superset:/app
    #mongobi://mongo_bi:3307/shield_db

  graph:
    build: ./EntrypointGraphAPI
    command: ./entrypoint.sh
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  # react-app:
  #   container_name: react_app
  #   restart: on-failure
  #   build: .
  #   volumes:
  #         - ./src:/app/src
  #   ports:
  #         - "3000:3000"
  #   command: >
  #         sh -c "yarn start"
volumes:
  mongo_data:
