# Generated by Django 4.1.4 on 2022-12-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email_address', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='M', max_length=1, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50)),
                ('office_location', models.CharField(max_length=256)),
                ('mobile_phone', models.CharField(max_length=10)),
                ('date_of_bith', models.DateTimeField()),
                ('employment_date', models.DateTimeField()),
                ('team', models.CharField(max_length=256)),
                ('project', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('organization', models.CharField(max_length=256)),
                ('martial_status', models.CharField(default='single', max_length=10, null=True)),
                ('address', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('hierarchical_superior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('received_datetime', models.DateTimeField()),
                ('sent_datetime', models.DateTimeField()),
                ('has_attachments', models.BooleanField()),
                ('subject', models.CharField(max_length=256)),
                ('is_read', models.BooleanField()),
                ('is_draft', models.BooleanField()),
                ('from_name', models.CharField(max_length=256)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_recipients', models.JSONField()),
                ('cc_recipients', models.JSONField()),
                ('bcc_recipients', models.JSONField()),
                ('reply_to', models.JSONField()),
                ('if_forwarded', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.userprofile')),
            ],
        ),
    ]
