# Generated by Django 3.0.5 on 2020-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialGraph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msemail',
            name='ai_predicted_sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='msemail',
            name='ai_predicted_topic',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
