# Generated by Django 3.0.5 on 2020-06-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialGraph', '0002_auto_20200605_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissue',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
