# Generated by Django 3.0.5 on 2020-06-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialGraph', '0003_auto_20200605_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiraissue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
