# Generated by Django 3.0.5 on 2020-06-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialGraph', '0004_auto_20200605_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='msemail',
            name='delta_time_for_each_msg',
            field=models.IntegerField(blank=True, default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='msemail',
            name='importance',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=10),
        ),
        migrations.AddField(
            model_name='msemail',
            name='is_work_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msemail',
            name='size',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='msemail',
            name='to_boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msemail',
            name='to_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msemailrecipient',
            name='delta_time_for_each_msg',
            field=models.IntegerField(blank=True, default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='msemailrecipient',
            name='from_boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msemailrecipient',
            name='from_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msemailrecipient',
            name='is_work_related',
            field=models.BooleanField(default=False),
        ),
    ]
