# Generated by Django 3.0.5 on 2020-06-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialGraph', '0005_auto_20200615_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msemail',
            name='delta_time_for_each_msg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='msemail',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msemailrecipient',
            name='delta_time_for_each_msg',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
