# Generated by Django 3.0.5 on 2020-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialGraph', '0006_auto_20200615_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(max_length=10)),
                ('total_recipients', models.IntegerField()),
            ],
            options={
                'db_table': 'email_summary',
                'managed': False,
            },
        ),
    ]
