# Generated by Django 3.0.5 on 2020-06-18 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialGraph', '0008_auto_20200618_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackMessageRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('cm', 'Channel Message'), ('dm', 'Direct Message')], max_length=20)),
                ('from_boss', models.BooleanField(default=False)),
                ('from_team', models.BooleanField(default=False)),
                ('delta_time_for_each_msg', models.IntegerField(blank=True, default=0)),
                ('is_work_related', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('slack_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialGraph.SlackMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
