# Generated by Django 3.0.5 on 2020-06-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialGraph', '0009_slackmessagerecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='jira_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socialGraph.JiraProject'),
            preserve_default=False,
        ),
    ]
