# Generated by Django 3.0.5 on 2020-06-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialGraph', '0010_jiraissue_jira_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_task', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'task_summary',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='is_on_time',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
