# Generated by Django 3.0.5 on 2020-06-22 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialGraph', '0011_auto_20200619_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='msteammessage',
            name='ai_predicted_sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='msteammessage',
            name='ai_predicted_topic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='msteammessage',
            name='ai_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msteammessage',
            name='delta_time_for_each_msg',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='msteammessage',
            name='is_work_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msteammessage',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='msteammessage',
            name='to_boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msteammessage',
            name='to_team',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MSTeamMessageRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('cm', 'Channel Message'), ('dm', 'Direct Message')], max_length=20)),
                ('from_boss', models.BooleanField(default=False)),
                ('from_team', models.BooleanField(default=False)),
                ('delta_time_for_each_msg', models.IntegerField(blank=True, default=0)),
                ('is_work_related', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ms_team_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialGraph.MSTeamMessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSTeamChannelMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ms_team_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialGraph.MSTeamChannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
