# Generated by Django 3.0.5 on 2020-07-01 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialGraph', '0012_auto_20200622_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSTeammsgSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_recipients', models.IntegerField()),
            ],
            options={
                'db_table': 'msteam_msg_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KPI_name', models.CharField(choices=[('collaboration', 'Collaboration'), ('productivity', 'Productivity'), ('communication', 'Communication'), ('burnout', 'Burnout'), ('selfish_worker', 'Selfish Worker'), ('motivation', 'Motivation  (Toxicity Level)'), ('moral', 'Moral'), ('collective_intelligence', 'Collective Intelligence')], max_length=50)),
                ('KPI_value', models.FloatField()),
                ('Kpi_avg', models.FloatField()),
                ('KPI_max_value', models.FloatField()),
                ('Kpi_min_value', models.FloatField()),
                ('Kpi_percentage', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
