# Generated by Django 3.0.5 on 2020-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialGraph', '0014_auto_20200701_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPISummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KPI_name', models.CharField(max_length=50)),
                ('vgood', models.IntegerField()),
                ('good', models.IntegerField()),
                ('neutral', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('vbad', models.IntegerField()),
            ],
            options={
                'db_table': 'kpi_summary',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
