app_id: "5220e68b-5be4-4194-9ced-3981d71d003b"
app_secret: "uRiVX.wo5hhdwec1ph/L0wJGCg2]@4Vx"
redirect: "http://localhost:8000/socialGraph/callback"
scopes: "openid profile offline_access user.read calendars.read Mail.Read User.Read.All Mail.ReadWrite Team.ReadBasic.All TeamMember.Read.All ChannelMessage.Read.All Channel.ReadBasic.All ChannelMember.Read.All GroupMember.Read.All"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
